src/pagalotodo-ucab-web/Models/Views/ActualizarConsumidorViewModel.cs
using UCABPagaloTodoWeb.Models.Responses;
using UCABPagaloTodoWeb.Models.Responses.Data;

namespace UCABPagaloTodoWeb.Models.Views
{
    public class ActualizarConsumidorViewModel:IBaseViewModel
    {
        private LoginDataModel loginDataModel {  get; set; }

        public ActualizarUsuarioDataModel actualizarUsuarioIdResponse { get; set; }

		public ActualizarConsumidorViewModel()
		{
			loginDataModel = new LoginDataModel();
			actualizarUsuarioIdResponse = new ActualizarUsuarioDataModel();
		}
		public ActualizarConsumidorViewModel(LoginDataModel _loginDataModel, ActualizarUsuarioDataModel _actualizarUsuarioIdResponse)
        {
            loginDataModel = _loginDataModel;
            actualizarUsuarioIdResponse = _actualizarUsuarioIdResponse;
        }
        
        public LoginDataModel obtenerLoginDataModel() => loginDataModel;

        public string obtenerUsuario() => loginDataModel.usuario;
    }
}

src/pagalotodo-ucab-web/Models/Views/MenuAdministradorViewModel.cs
using UCABPagaloTodoWeb.Models.Responses;

namespace UCABPagaloTodoWeb.Models.Views
{
    public class MenuAdministradorViewModel : IBaseViewModel
    {
        private LoginDataModel? loginDataModel { get; set; }

        public MenuAdministradorViewModel(LoginDataModel _loginDataModel) 
        {
            loginDataModel = _loginDataModel;
        }
        public string obtenerUsuario()
        {
            return loginDataModel.usuario;
        }
        public LoginDataModel obtenerLoginDataModel() => loginDataModel;
    }
}

src/pagalotodo-ucab-web/Models/Views/VerUsuariosViewModel.cs
using System.Runtime.CompilerServices;
using UCABPagaloTodoWeb.Models.Responses;

namespace UCABPagaloTodoWeb.Models.Views
{
    public class VerUsuariosViewModel : IBaseViewModel
    {
        private LoginDataModel? loginDataModel { get; set; }
        private ConsultarUsuariosResponse? consultarUsuarioResponse { get; set; }

        public string obtenerUsuario() => loginDataModel.usuario;

        public LoginDataModel obtenerLoginDataModel() => loginDataModel;

        public UsuarioDataModel[] obtenerUsuarios() => consultarUsuarioResponse.data;

        public VerUsuariosViewModel(LoginDataModel _loginDataModel, ConsultarUsuariosResponse _consultarUsuarioResponse) {
            loginDataModel= _loginDataModel;
            consultarUsuarioResponse= _consultarUsuarioResponse;
        }
    }
}

src/pagalotodo-ucab-web/Controllers/MenuAdministradorController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using System.Text.Json.Nodes;
using UCABPagaloTodoWeb.Models;
using UCABPagaloTodoWeb.Models.Requests;
using UCABPagaloTodoWeb.Models.Responses;
using UCABPagaloTodoWeb.Models.Views;

namespace UCABPagaloTodoWeb.Controllers
{
    public class MenuAdministradorController : Controller
    {
        private readonly ILogger<MenuAdministradorController> _logger;
        private readonly HttpClient _httpClient;

        public MenuAdministradorController(ILogger<MenuAdministradorController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }

        public IActionResult MenuAdministrador(LoginDataModel loginDataModel)
        {
            MenuAdministradorViewModel menuAdministradorViewModel = new MenuAdministradorViewModel(loginDataModel);
            return View(menuAdministradorViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> VerUsuarios(LoginDataModel loginDataModel)
        {
            var api = "https://localhost:44339/crudusuarios/consultarusuarios";
            var response = await _httpClient.GetAsync(api);
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var consultarUsuariosResponse = JsonConvert.DeserializeObject<ConsultarUsuariosResponse>(responseContent);
                if (consultarUsuariosResponse.data.Length > 0)
                {
                    VerUsuariosViewModel consultarUsuariosViewModel=new VerUsuariosViewModel(loginDataModel, consultarUsuariosResponse);

                    return View(consultarUsuariosViewModel);
                }
                return RedirectToAction("Privacy", "Home");

            }
            return RedirectToAction("Privacy", "Home");
            
        }



        [HttpGet]
        public async Task<IActionResult> ConsultarUsuario(string usuarioLogin, string discriminatorLogin, Guid idLogin, Guid id)
        {
            LoginDataModel loginDataModel = new LoginDataModel(idLogin, discriminatorLogin, usuarioLogin);  
            var api = "https://localhost:44339/crudusuarios/consultarusuarioid?id_usuario="+id;
            var response = await _httpClient.GetAsync(api);
                
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var consultarUsuarioIdResponse = JsonConvert.DeserializeObject<ConsultarUsuarioIdResponse>(responseContent);
                if (consultarUsuarioIdResponse.data.Length > 0)
                {
                        ActualizarConsumidorViewModel actualizarConsumidorViewModel = new ActualizarConsumidorViewModel(loginDataModel, consultarUsuarioIdResponse.data[0]);
                    if (consultarUsuarioIdResponse.data[0].Discriminator == "Consumidor")
                    {
                        return RedirectToAction("ActualizarConsumidor",actualizarConsumidorViewModel);
                    }
                    return RedirectToAction("Privacy", "Home");
                }
                    return RedirectToAction("Privacy", "Home");

                }
            return RedirectToAction("Privacy", "Home");
        }

        public IActionResult ActualizarConsumidor(ActualizarConsumidorViewModel actualizarConsumidorViewModel)
        {
            return View(actualizarConsumidorViewModel);
        }
        



        [HttpPost]
        public async Task<IActionResult> RegistrarConsumidor(AgregarConsumidorRequestModel requestBody)
        {
            //enviar preguntas al backend para mostrarlas

            var api = "https://localhost:44339/crudusuarios/agregarconsumidor";
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            });
            var response = await _httpClient.PostAsync(api, new StringContent(jsonBody, Encoding.UTF8, "application/json"));
            if (response.IsSuccessStatusCode)
            {

                var responseContent = await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<LoginResponse>(responseContent);
                if (loginResponse.data[0].id != Guid.Empty)
                {
                    //Si es correcto
                    return RedirectToAction("MensajeExitoAgregarConsumidor", "Mensajes");
                }
                return RedirectToAction("Privacy", "Home");

            }
            return RedirectToAction("Privacy", "Home");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/pagalotodo-ucab-web/Controllers/RecuperarClaveController.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using UCABPagaloTodoWeb.Models;
using UCABPagaloTodoWeb.Models.Requests;
using UCABPagaloTodoWeb.Models.Responses;

namespace UCABPagaloTodoWeb.Controllers
{
    public class RecuperarClaveController : Controller
    {
        private readonly ILogger<RecuperarClaveController> _logger;
        private readonly HttpClient _httpClient;

        public RecuperarClaveController(ILogger<RecuperarClaveController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }

        public IActionResult RecuperarClave()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ValidarRespuestas(ConsultarRespuestasDeSeguridadModel datos)
        {
            var api = "https://localhost:44339/crudusuarios/preguntasdeseguridad?password=";
            api += datos.usuario;
            var response = await _httpClient.GetAsync(api);
            if (response.IsSuccessStatusCode)
            {

                var responseContent = await response.Content.ReadAsStringAsync();
                var jsonResponse = JsonConvert.DeserializeObject<PreguntasDeSeguridadResponse>(responseContent);
                var preguntas = new PreguntasDeSeguridadModel();
                preguntas.pregunta_de_seguridad = jsonResponse.data[0].pregunta_de_seguridad;
                preguntas.pregunta_de_seguridad2 = jsonResponse.data[0].pregunta_de_seguridad2;
                if (preguntas != null)
                {
                    return RedirectToAction("ConsultarRespuestas", preguntas);
                }
                return RedirectToAction("Privacy", "Home", preguntas);

            }
            return RedirectToAction("Privacy", "Home");
        }


        public IActionResult ConsultarRespuestas(PreguntasDeSeguridadModel preguntas)
        {
            ViewData["pregunta_de_seguridad"] = preguntas.pregunta_de_seguridad;
            ViewData["pregunta_de_seguridad2"] = preguntas.pregunta_de_seguridad2;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ConsultarRespuestas(RecuperarClaveRequestModel datos)
        {
            var api = "https://localhost:44339/crudusuarios/preguntasdeseguridad?usuario=";
            api += datos.usuario;
            var response = await _httpClient.GetAsync(api);
            if (response.IsSuccessStatusCode)
            {

                var responseContent = await response.Content.ReadAsStringAsync();
                var jsonResponse = JsonConvert.DeserializeObject<PreguntasDeSeguridadResponse>(responseContent);
                var preguntas = new PreguntasDeSeguridadModel();
                preguntas.pregunta_de_seguridad = jsonResponse.data[0].pregunta_de_seguridad;
                preguntas.pregunta_de_seguridad2 = jsonResponse.data[0].pregunta_de_seguridad2;
                if (preguntas != null)
                {
                    return RedirectToAction("ConsultarRespuestas", preguntas);
                }
                return RedirectToAction("Privacy", "Home", preguntas);
            
            }
            return RedirectToAction("Privacy", "Home");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/pagalotodo-ucab-web/Views/MenuAdministrador/ActualizarConsumidor.cshtml
@{
    Layout = "~/Views/Shared/_MenuAdministradorLayout.cshtml";
}

@using UCABPagaloTodoWeb.Models.Views;
@using UCABPagaloTodoWeb.Models.Responses;
@model ActualizarConsumidorViewModel;

<section class="py-5 my-5">
	<div class="container">
		<div class="bg-white shadow rounded-lg d-block d-sm-flex">
			<div class="profile-tab-nav border-right">
				<div class="p-4">
					<div class="img-circle text-center mb-3">
						<img src="~/img/user.jfif" alt="Image" class="shadow">
					</div>
					<br />
					<br />
					<h4 class="text-center">NOMBRE USUARIO</h4> <!-- Aqui va el nombre de usuario del request -->
				</div>
				<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">

				</div>
			</div>



			<!-- Esta es la parte de cambiar cuenta -->
			<div class="tab-content p-4 p-md-5" id="v-pills-tabContent">
				<div class="tab-pane fade show active" id="account" role="tabpanel" aria-labelledby="account-tab">
					<h3 class="mb-4">Actualizar Cuenta</h3>
					<div class="row">

						<!-- Usuario -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Usuario</label>
								<input type="text" class="form-control" value="@Model.">
							</div>
						</div>

						<!-- Contraseña -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Contraseña</label>
								<input type="text" class="form-control" value="">
							</div>
						</div>

						<!-- Correo -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Correo</label>
								<input type="text" class="form-control" value="@Model.actualizarUsuarioIdResponse.correo">
							</div>
						</div>

						<!-- Nombre -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Nombre</label>
								<input type="text" class="form-control" value="@Model.actualizarUsuarioIdResponse.nombre">
							</div>
						</div>

						<!-- Cedula -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Cedula</label>
								<input type="text" class="form-control" value="@Model.actualizarUsuarioIdResponse.ci">
							</div>
						</div>

						<!-- Preguntas de seguridad y respuestas de seguridad 1 -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Pregunta de seguridad 1</label>
								<input type="text" class="form-control" value="Pregunta">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>Respuesta de seguridad 1</label>
								<input type="text" class="form-control" value="RespuestaSeguridadRequest1">
							</div>
						</div>

						<!-- Preguntas de seguridad y respuestas de seguridad 2 -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Pregunta de seguridad 2</label>
								<input type="text" class="form-control" value="PreguntaSeguridadRequest2">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>Respuesta de seguridad 2</label>
								<input type="text" class="form-control" value="RespuestaSeguridadRequest2">
							</div>
						</div>

						<!-- Estado -->
						<div class="col-md-6">
							<div class="form-group">
								<label>Estado</label>
								<select>
									<option value="Activo">Activo</option>
									<option value="Inactivo">Inactivo</option>
								</select>
							</div>
						</div>


					</div>
					<div class="botones">
						<button class="btn btn-primary">Actualizar</button>
						
						@using (Html.BeginForm("VerUsuarios", "MenuAdministrador", FormMethod.Post)){
							<div hidden>
							@Html.HiddenFor(id=>Model.obtenerLoginDataModel().id);
							@Html.HiddenFor(usuario=>Model.obtenerLoginDataModel().usuario);
							@Html.HiddenFor(discriminator=>Model.obtenerLoginDataModel().discriminator);
							</div>
							<button class="btn btn-light">Cancelar</button>
						}
						
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

src/pagalotodo-ucab-web/Views/MenuAdministrador/MenuAdministrador.cshtml
@{
    Layout = "~/Views/Shared/_MenuAdministradorLayout.cshtml";
}

<body>
    <div class="container" id="container">
        <div class="form-container registrarse-container">
            @using (Html.BeginForm("ValidarRespuestas", "RecuperarClave", FormMethod.Post))
            {
                <h1>Recuperar Clave</h1>
                <div>
                    <label>Indica tu nueva clave</label>
                    <input type="password" name="password" required>
                </div>
                <p>Responde las preguntas de seguridad</p>
                <div>
                    <label>@ViewData["pregunta_de_seguridad"]</label>
                    <input type="text" name="respuesta1" required>
                </div>
                <div>
                    <label>@ViewData["pregunta_de_seguridad2"]</label>
                    <input type="text" name="respuesta2" required>
                </div>
                <button>Aceptar</button>
            }
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1 class="title">Preguntas de Seguridad</h1>
                    <p>Responde las siguientes preguntas para poder asegurarnos que seas tú en realidad</p>
                </div>
            </div>
        </div>
    </div>
</body>

src/pagalotodo-ucab-web/Views/MenuAdministrador/VerUsuarios.cshtml
@{
    Layout = "~/Views/Shared/_MenuAdministradorLayout.cshtml";
}

@using UCABPagaloTodoWeb.Models.Views;
@using UCABPagaloTodoWeb.Models.Responses;
@model VerUsuariosViewModel;

<div id="usuarios-content" class="content">
    <h2>Usuarios</h2>

    <!-- Campo de búsqueda por nombre -->
    <div>
        <label for="buscar-nombre">Buscar por nombre:</label>
        <input type="text" id="buscar-nombre">
        <button type="button" id="buscar-boton" onclick="buscarPorNombre()">Buscar</button>
    </div>

    <!-- Tabla de usuarios -->
    <table id="tabla-usuarios">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Correo electrónico</th>
            </tr>
        </thead>
        <tbody>
            
                @foreach(UsuarioDataModel usuario in Model.obtenerUsuarios())
                {             
                    <tr>
                    <td><a href="@Url.Action("ActualizarConsumidor","MenuAdministrador", new{idLogin=Model.obtenerLoginDataModel().id, usuarioLogin=Model.obtenerUsuario(), discriminatorLogin=Model.obtenerLoginDataModel().discriminator, id=@usuario.id_usuario})">@usuario.id_usuario</a></td>
                    <td>@usuario.nombre</td>
                    <td>@usuario.correo</td>
                    </tr>
                }
        </tbody>
    </table>
</div>