src/pagalotodo-ucab-web/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Security.Claims;
using UCABPagaloTodoWeb.Models;
using System.Text;
using UCABPagaloTodoWeb.Models.Responses;
using UCABPagaloTodoWeb.Models.Views;
using UCABPagaloTodoWeb.Models.Requests;

namespace UCABPagaloTodoWeb.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly HttpClient _httpClient;
            public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }

        public IActionResult Login(LoginRequestModel credenciales)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ValidarCredenciales(LoginRequestModel requestBody)
        {
            var api = "https://localhost:44339/crudusuarios/loginusuario";
            var jsonBody=JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            });
            var response = await _httpClient.PostAsync(api, new StringContent(jsonBody, Encoding.UTF8, "application/json"));
            if (response.IsSuccessStatusCode)
            {
               
                var responseContent=await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<LoginResponse>(responseContent);
                if (loginResponse.data[0].id!=Guid.Empty)
                {
                    return RedirectToAction("loginAdministrador", loginResponse.data[0]);
                    
                }
                return RedirectToAction("Privacy", "Home");
                
            }
            return RedirectToAction("Privacy", "Home");
        }

        public IActionResult loginAdministrador(LoginDataModel loginDataModel)
        {
            if (loginDataModel.discriminator == "Administrador")
            {
                return RedirectToAction("MenuAdministrador", "MenuAdministrador", loginDataModel);
            }
            else
            {
                return RedirectToAction("loginConsumidor", loginDataModel);
            }
        }

        public IActionResult loginConsumidor(LoginDataModel loginDataModel)
        {
            if (loginDataModel.discriminator == "Consumidor")
            {
                return RedirectToAction("MenuAdministrador", "MenuAdministrador", loginDataModel);
            }
            else
            {
                return RedirectToAction("loginPrestador", loginDataModel);
            }
        }

        public IActionResult loginPrestador(LoginDataModel loginDataModel)
        {
            if (loginDataModel.discriminator == "Prestador")
            {
                return RedirectToAction("MenuAdministrador", "MenuAdministrador", loginDataModel);
            }
            else
            {
                return RedirectToAction("loginPrestador", loginDataModel);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/pagalotodo-ucab-web/Controllers/RegistrarUsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using UCABPagaloTodoWeb.Models;
using UCABPagaloTodoWeb.Models.Requests;
using UCABPagaloTodoWeb.Models.Responses;

namespace UCABPagaloTodoWeb.Controllers
{
    public class RegistrarUsuarioController : Controller
    {
        private readonly ILogger<RegistrarUsuarioController> _logger;
        private readonly HttpClient _httpClient;

        public RegistrarUsuarioController(ILogger<RegistrarUsuarioController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }

        public IActionResult RegistrarUsuario()
        {
            //envie datos con el servicio
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> RegistrarConsumidor(AgregarConsumidorRequestModel requestBody)
        {
            //enviar preguntas al backend para mostrarlas

            var api = "https://localhost:44339/crudusuarios/agregarconsumidor";
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            });
            var response = await _httpClient.PostAsync(api, new StringContent(jsonBody, Encoding.UTF8, "application/json"));
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<RegistrarUsuarioResponse>(responseContent);
                if (loginResponse.data != Guid.Empty)
                {
                    //Si es correcto
                    return RedirectToAction("MensajeExitoAgregarConsumidor", "Mensajes");
                }
                return RedirectToAction("Privacy", "Home");

            }
            return RedirectToAction("Privacy", "Home");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/pagalotodo-ucab-web/Views/Login/Login.cshtml
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<body>
    <div class="container" id="container">

        <div class="form-container registrarse-container">
            @using (Html.BeginForm("RegistrarConsumidor", "RegistrarUsuario", FormMethod.Post))
            {
                <h1>Registrarse</h1>
                <input type="text" placeholder="Cédula" name="ci" required>
                <input type="text" placeholder="Nombres" name="nombre" required>
                <input type="text" placeholder="Apellidos" name="apellido" required>
                <input type="text" placeholder="Usuario" name="usuario" required>
                <input type="email" placeholder="Correo" name="correo" required>
                <input type="password" placeholder="Contraseña" name="password" required>
                <select name="preguntas_de_seguridad" id="preguntas">
                    <option value="¿Cuál es el nombre de tu mascota?">¿Cuál es el nombre de tu mascota?</option>
                    <option value="¿Cuál es tu color favorito?">¿Cuál es tu color favorito?</option>
                    <option value="¿En qué ciudad naciste?">¿En qué ciudad naciste?</option>
                    <option value="¿Cuál es el nombre de soltera de tu madre?">¿Cuál es el nombre de soltera de tu madre?</option>
                    <option value="¿Cuál es tu comida favorita?">¿Cuál es tu comida favorita?</option>
                </select>
                <input type="text" placeholder="Respuesta" name="respuesta_de_seguridad">
                <select name="preguntas_de_seguridad2" id="preguntas">
                    <option value="¿Cuál es el nombre de tu mascota?">¿Cuál es el nombre de tu mascota?</option>
                    <option value="¿Cuál es tu color favorito?">¿Cuál es tu color favorito?</option>
                    <option value="¿En qué ciudad naciste?">¿En qué ciudad naciste?</option>
                    <option value="¿Cuál es el nombre de soltera de tu madre?">¿Cuál es el nombre de soltera de tu madre?</option>
                    <option value="¿Cuál es tu comida favorita?">¿Cuál es tu comida favorita?</option>
                </select>
                <input type="text" placeholder="Respuesta" name="respuesta_de_seguridad2">
                <button>registrarse</button>
            }
        </div>

        <div class="form-container login-container">
            @using (Html.BeginForm("ValidarCredenciales", "Login", FormMethod.Post))
            {
                <h1>Iniciar sesión</h1>
                <input type="text" placeholder="Usuario" name="usuario">
                <input type="password" placeholder="Contraseña" name="password">
                <div class="content">
                    <div class="pass-link">
                        <a href="@Url.Action("RecuperarClave", "RecuperarClave")">¿Has olvidado tu contraseña?</a>
                    </div>
                </div>
                <button>Comenzar</button>
            }
        </div>

        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <img src="~/img/logo.png" class="logo">
                    <br />
                    <br />
                    <h1 class="title">Bienvenidos a <br> nuestra plataforma</h1>
                    <p>Si tienes una cuenta, inicia sesión aquí y diviértete</p>
                    <button class="ghost" id="login">
                        Login
                        <i class="lni lni-arrow-left login"></i>
                    </button>
                </div>
                
                <div class="overlay-panel overlay-right">
                    <img src="~/img/logo.png" class="logo">
                    <br />
                    <br />
                    <h1 class="title">Comienza tu<br>viaje con<br>Pagalo Todo Ucab</h1>
                    <p>Si aún no tiene una cuenta, únase a nosotros y comience su viaje.</p>
                    <button class="ghost" id="registrarse">
                        registrarse
                        <i class="lni lni-arrow-right registrarse"></i>
                    </button>
                </div>
            </div>
        </div>

    </div>

</body>
</html>